name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY : true

jobs:
  test:
    name: Test
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        # TODO: Below can be removed when https://github.com/actions-rs/toolchain/issues/126 is resolved
        with:
          toolchain: nightly-2022-02-15
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt , clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cargo Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
#  TODO: see https://github.com/actions-rs/clippy-check#limitations 
      # - uses: actions-rs/clippy-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # args: -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-15
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests --avoid-cfg-tarpaulin'

